# name: Deploy Lambda Function
# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Zip Lambda function
#         run: zip -r lambda.zip lambda.py

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-2

#       - name: Deploy to Lambda
#         run: |
#           aws lambda update-function-code --function-name arn:aws:lambda:us-east-2:654654366158:function:ClearingHouse2 --zip-file fileb://lambda.zip

name: Deploy Lambda Function
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Assume IAM role
        run: |
          aws sts assume-role --role-arn arn:aws:iam::123456789012:role/YourRoleName --role-session-name GitHubActionsSession > assumed-role.json
          export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' assumed-role.json)
          export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' assumed-role.json)
          export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' assumed-role.json)

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name arn:aws:lambda:us-east-2:654654366158:function:ClearingHouse2 --zip-file fileb://lambda.zip