name: Deploy Lambda Function
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Lambda function
        run: zip -r lambda.zip lambda.py  # Assuming lambda.py is in the root directory

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name arn:aws:lambda:us-east-2:654654366158:function:ClearingHouse2 --zip-file fileb://lambda.zip
